export const RECEIVE_MOVIES = 'RECEIVE_MOVIES',
						 RECEIVE_CATEGORY = 'RECEIVE_CATEGORY',
						 USER_MOVIES = 'USER_MOVIES',
						 SIGNED_USER = 'SIGNED_USER',
						 SEARCH = 'SEARCH',
						 REGISTER = 'REGISTER',
						 MOVIE_SELECTED = 'MOVIE_SELECTED',
						 USER_MOVIES_SELECTED = 'USER_MOVIES_SELECTED';