export const RECEIVE_MOVIES = 'RECEIVE_MOVIES',
						 RECEIVE_CATEGORY = 'RECEIVE_CATEGORY',
						 USER_LAST_MOVIE = 'USER_LAST_MOVIE',
						 SIGNED_USER = 'SIGNED_USER',
						 SEARCH = 'SEARCH',
						 REGISTER = 'REGISTER',
						 MOVIE_SELECTED = 'MOVIE_SELECTED';